"""Remove task_id field from Scan model.

Revision ID: 193a7961fa93
Revises: c3862fae5020
Create Date: 2022-10-22 16:24:32.231809

"""

# revision identifiers, used by Alembic.
from alembic import context, op
import sqlalchemy as sa
revision = '193a7961fa93'
down_revision = 'c3862fae5020'


def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_upgrades()


def downgrade():
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_downgrades()
    schema_downgrades()


def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan', 'task_id')
    # ### end Alembic commands ###


def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan', sa.Column('task_id', sa.INTEGER(),
                  autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass


def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass
