"""Fix Device model

Revision ID: 262825ca869a
Revises: d524b4b7cd21
Create Date: 2022-09-30 18:09:24.849183

"""

# revision identifiers, used by Alembic.
revision = '262825ca869a'
down_revision = 'd524b4b7cd21'

from alembic import op
import sqlalchemy as sa


from alembic import context


def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_upgrades()

def downgrade():
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_downgrades()
    schema_downgrades()

def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan', sa.Column('task_id', sa.Integer(), nullable=True))
    op.drop_column('scan', 'scan_id')
    # ### end Alembic commands ###

def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan', sa.Column('scan_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('scan', 'task_id')
    # ### end Alembic commands ###

def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass

def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass