"""Model fixes

Revision ID: d524b4b7cd21
Revises: 824e15196310
Create Date: 2022-09-29 18:53:27.794538

"""

# revision identifiers, used by Alembic.
revision = 'd524b4b7cd21'
down_revision = '824e15196310'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import context


def upgrade():
    schema_upgrades()
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_upgrades()

def downgrade():
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_downgrades()
    schema_downgrades()

def schema_upgrades():
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan', sa.Column('scan_id', sa.Integer(), nullable=True))
    op.add_column('scan', sa.Column('start', sa.DateTime(), nullable=True))
    op.add_column('scan', sa.Column('finish', sa.DateTime(), nullable=True))
    op.drop_column('scan', 'scan_time_finish')
    op.drop_column('scan', 'scan_time_start')
    # ### end Alembic commands ###

def schema_downgrades():
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan', sa.Column('scan_time_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('scan', sa.Column('scan_time_finish', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('scan', 'finish')
    op.drop_column('scan', 'start')
    op.drop_column('scan', 'scan_id')
    # ### end Alembic commands ###

def data_upgrades():
    """Add any optional data upgrade migrations here!"""
    pass

def data_downgrades():
    """Add any optional data downgrade migrations here!"""
    pass